package com.example.excel.model;

public enum UserState {
    DEFAULT,
    WAITING_FOR_INCOME_WITH_DESCRIPTION,
    WAITING_FOR_EXPENSE_WITH_DESCRIPTION,
    WAITING_FOR_UPDATE_INCOME,
    WAITING_FOR_UPDATE_EXPENSE,
    WAITING_FOR_POINT_SELECTION,
    WAITING_FOR_POINT_NAME,
    WAITING_FOR_DELETE_INCOME,
    WAITING_FOR_DELETE_EXPENSE,
    WAITING_FOR_DELETE_POINT,
    WAITING_FOR_REGISTRATION_PASSWORD
}