package com.example.excel.model;

public enum UserState {
    NONE,
    WAITING_FOR_INCOME,
    WAITING_FOR_EXPENSE,
    WAITING_FOR_UPDATE,
    WAITING_FOR_PASSWORD,
    WAITING_FOR_INCOME_WITH_DESCRIPTION,
    WAITING_FOR_EXPENSE_WITH_DESCRIPTION
}
